name: Python application

on: 
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest  # Include any other dependencies your project needs

    - name: Run flake8
      run: flake8 .  # This will check all Python files in the repository

    - name: Run pytest
      run: pytest  # This will run your tests
